store_app/store/views/views.py
""" This is the main routes module """
from flask import render_template, Blueprint, redirect, flash, request
from datetime import date
from ..service import *
from ..forms import CreateClientForm, CreateOrderForm, CreateProductForm, DeleteItem, Filters

bp = Blueprint('bp', __name__, template_folder="bp")


@bp.route('/')
@bp.route('/clients')
def clients():
    """ The main (clients) page """
    form = Filters()
    date_from = request.args.get('date_from')
    date_to = request.args.get('date_to')
    if date_from is not None and date_to is not None:
        data = get_clients_list(True, date_from=date_from, date_to=date_to)
        if data == []:
            flash("No rows found")
    else:
        data = get_clients_list(False)
    return render_template('bp/clients.html', page='client', data=data, form=form)


@bp.route('/new_client', methods=['GET', 'POST'])
def new_client():
    """ Client creation page """
    form = CreateClientForm()
    if form.cancel.data:
        return redirect('/clients')
    else:
        if form.validate_on_submit():
            email=form.email.data
            phone=form.phone.data
            if Client.query.filter(Client.email == email).first():
                flash("Email already in use")
            elif Client.query.filter(Client.phone == phone).first():
                flash("Phone number already in use")
            else:
                edit_item(Client(first_name=form.first_name.data, last_name=form.last_name.data,
                                email=form.email.data, phone=form.phone.data, date=date.today()))
                return redirect('/clients')
    return render_template('bp/manipulate_client.html', page='client', form=form)


@bp.route('/edit_client/<int:id>', methods=['GET', 'POST'])
def edit_client(id):
    """ Product creation page """
    client = get_item_with_filter(Client, Client.id, id)
    if client is None:
        flash("There's no product with id {}".format(id))
        return redirect('/clients')
    else:
        form = CreateClientForm(first_name=client.first_name, last_name=client.last_name,\
                                email=client.email, phone=client.phone)
        if form.cancel.data:
            return redirect('/clients')
        else:
            if form.validate_on_submit():
                if form.submit.data:
                    client.first_name=form.first_name.data
                    client.last_name=form.last_name.data
                    client.email=form.email.data
                    client.phone=form.phone.data
                    edit_item(client)
                    return redirect('/clients')
    return render_template('bp/manipulate_client.html', page='client', form=form)


@bp.route('/delete_client/<int:id>', methods=['GET', 'POST'])
def delete_client(id):
    """ Delete confirm page """
    form = DeleteItem()
    if form.cancel.data:
        return redirect('/clients')
    else:
        if form.validate_on_submit():
            client = get_item_with_filter(Client, Client.id, id)
            if client is None:
                flash("There's no client with id {}".format(id))
                return redirect('/clients')
            delete_item(client)
            return redirect('/clients')
    return  render_template('bp/delete_item.html', type="new", form=form, item = "client", id = id)


@bp.route('/orders')
def orders():
    """ The orders page """
    form=Filters()
    items=[]
    date_from = request.args.get('date_from')
    date_to = request.args.get('date_to')
    if date_from is not None and date_to is not None:
        data, order = get_orders_list(True, date_from=date_from, date_to=date_to)
        if data == []:
            flash("No rows found")
    else:
        data, order = get_orders_list(False)

    for item in order:
        items.append(', '.join(item))
    return render_template('bp/orders.html', page='order', data=data, len=len(data), order=items, form=form)


@bp.route('/new_order', methods=['GET', 'POST'])
def new_order():
    """ Order creation page """
    form = CreateOrderForm()
    if form.cancel.data:
        return redirect('/orders')
    else:
       if form.validate_on_submit():
            full_name = form.name.data
            phone = form.phone.data
            positions = form.order.data
            client = get_item_with_filter(Client, Client.phone, phone)
            if client and client.first_name+' '+client.last_name == full_name:
                name = full_name.split(" ")
                order_list = positions.split(", ")
                available = True
                if len(order_list) != len(set(order_list)):
                    flash("You can order only 1 unit per product")
                    available=False

                cost = 0
                items=[]
                checked = []
                if name[0] == client.first_name and name[1] == client.last_name:

                    for item in order_list:
                        checked.append(item)
                        product = get_item_with_filter(Product, Product.name, item)
                        validate_order(item, product)

                    if available is True:
                        order = Order(date=form.date.data, user_id=client.id, cost=cost,
                                              address=form.address.data, products=items)

                        for item in checked:
                            buf = get_item_with_filter(Product, Product.name, item)
                            order.cost += buf.cost
                            order.products.append(buf)
                            buf.amount-=1
                            commit()
                        create_item(order)
            else:
                flash("No client with this data")
            return redirect('/orders')
    return render_template('bp/manipulate_order.html', page='order', form=form)


@bp.route('/edit_order/<int:id>', methods=['GET', 'POST'])
def edit_order(id):
    """ Product creation page """
    order = get_item_with_filter(Order, Order.id, id)
    if order is None:
        flash("There's no order with id {}".format(id))
        return redirect('/orders')
    client = get_item_with_filter(Client, Client.id, order.user_id)

    if client is None:
        flash("There's no client with id {}".format(id))
        return redirect('/orders')
    items = [i.name for i in order.products]
    items = ', '.join(items)
    if order is None:
        flash("There's no product with id {}".format(id))
        return redirect('/orders')
    else:
        form = CreateOrderForm(name=client.first_name+" "+client.last_name, phone=client.phone,\
                               order=items, address=order.address, date=order.date)
        if form.cancel.data:
            return redirect('/orders')
        else:
            if form.validate_on_submit():
                name = form.name.data.split(" ")
                phone = form.phone.data
                order_list = form.order.data.split(", ")
                if len(order_list) != len(set(order_list)):
                    flash("You can order only 1 unit per product")

                client = get_item_with_filter(Client, Client.phone, phone)
                if client:
                    checked=[]
                    if name[0] == client.first_name and name[1] == client.last_name:
                        available = True

                        for item in order_list:
                            checked.append(item)
                            product = get_item_with_filter(Product, Product.name, item)
                            available = validate_order(item, product)

                        if available is True:
                            order.cost=0
                            order.products=[]
                            for item in checked:
                                buf = get_item_with_filter(Product, Product.name, item)
                                order.cost+=buf.cost
                                order.products.append(buf)
                            order.date=form.date.data
                            edit_item(order)

                        else:
                            return redirect('/edit_order/'+str(id))
                        return redirect('/orders')
                else:
                    flash("No client with this data")
    return render_template('bp/manipulate_order.html', page='order', form=form)


@bp.route('/delete_order/<int:id>', methods=['GET', 'POST'])
def delete_order(id):
    """ The delete order confirm """
    form = DeleteItem()
    if form.cancel.data:
        return redirect('/orders')
    else:
        if form.validate_on_submit():
            order = get_item_with_filter(Order, Order.id, id)
            if order is None:
                flash("There's no order with id {}".format(id))
                return redirect('/orders')
            delete_item(order)
            return redirect('/orders')
    return  render_template('bp/delete_item.html', type="new", form=form, item = "order", id = id)


@bp.route('/products')
def products():
    """ The products page """
    form = Filters()
    price_from = request.args.get('price_from')
    price_to = request.args.get('price_to')
    if price_from is not None and price_to is not None:
        data = get_products_list(True, price_from=price_from, price_to=price_to)
        if data == []:
            flash("No rows found")
    else:
        data = get_products_list(False)
    return render_template('bp/products.html', page='product', data=data, len=len(data), form=form)


@bp.route('/new_product', methods=['GET', 'POST'])
def new_product():
    """ Product creation page """
    form = CreateProductForm()
    if form.cancel.data:
        return redirect('/clients')
    else:
        if form.validate_on_submit():
            name = form.name.data
            category = form.category.data
            year = form.year.data
            cost=form.cost.data

store_app/store/templates/bp/clients.html
{% extends "layout.html" %}
{% block content %}

        <div class="row">
                <form name="Filter", class="filter-form">
                    <div class="filter">
                    <label id="filter_by">Filter by date</label>
                    <span>{{ form.date_from.label }}
                        {{ form.date_from }}</span>
                    <span>{{ form.date_to.label }}
                    {{ form.date_to }}</span>
                        </div>
                    {{ form.refresh(class_="btn refresh-btn") }}

                </form>

        </div>
        <div class="list">
            <table class="table">
                <thead>
                    <tr>
                        <th class="column-id">Id</th>
                        <th class="column-f-name">First name</th>
                        <th class="column-l-name">Last name</th>
                        <th class="column-email">Email</th>
                        <th class="column-phone">Phone</th>
                        <th class="column-orders">Orders</th>
                        <th class="column-registration">Registration</th>
                        <th class="column-edit"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in data %}
                    <tr>
                        <td>{{ item.id }}</td>
                        <td>{{ item.first_name }}</td>
                        <td>{{ item.last_name }}</td>
                        <td>{{ item.email }}</td>
                        <td>{{ item.phone }}</td>
                        <td>{{ item.orders|length }}</td>
                        <td>{{ item.date }}</td>
                        <td class="edit-row"><a href="{{ url_for('bp.delete_client', id=item.id) }}"><i class="fa-solid fa-trash-can"></i></a>
                            <a href="{{ url_for('bp.edit_client', id=item.id) }}"><i class="fa-solid fa-gear"></i></a></td>
                    {% endfor %}
                    </tr>

                </tbody>
            </table>
        </div>
    </div>

</body>

{% endblock %}

store_app/store/templates/bp/delete_item.html
{% extends "layout.html" %}
{% block content %}

    <div class="center">
    <div class="block">
    <h3>Do you really want to delete {{ item }} with id = {{ id }} ?</h3>

    <form class="edit-form" name="Create client" method="post" novalidate>
        {{ form.hidden_tag() }}
        <div class="edit">
            {{ form.cancel( class_="cancel") }}
            {{ form.submit( class_="save" ) }}
        </div>
    </form>
    </div></div>
{% endblock %}

store_app/store/templates/bp/index.html
<!DOCTYPE html>
<html>
<head>
    <title>UTA - Home Page</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="static/css/main.css"/>
</head>
<body>

<div class="container-fluid text-center top-container">
    <img src="static/images/uta-logo-200.png">
</div>
<div class="container">

    {% include "includes/nav.html" %}
    
    <div class="row">
        <div class="col-md-12 text-center">
            <h1>Welcome to Universal Tech Academy.</h1>

            {% if login %}
            <h3>Let's get started.</h3>
            {% else %}
            <p>Already registered? <a href="{{url_for('login') }}">Login</a></p>
            {% endif %}

            </div>
    </div>
</div>

{% include "includes/footer.html" %}
</body>
</html>

store_app/store/templates/bp/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Management</title>
    <link type= "text/css" href= "../static/style.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://kit.fontawesome.com/3f636a5948.js" crossorigin="anonymous"></script>
</head>

<body>
    <h1 id="Management">Management page</h1>
    <div class="main_block">

        <div class="menu">
            <div class="left-side">
                <a class="btn   {% if page=="client" %} active-menu-btn"
                                {% else %} menu-btn"
                                {% endif %}
                href="{{ url_for('bp.clients') }}">Clients</a>
                <a class="btn   {% if page=="order" %} active-menu-btn"
                                {% else %} menu-btn"
                                {% endif %} href="{{ url_for('orders') }}">Orders</a>
                <a class="btn {% if page=="product" %} active-menu-btn"
                                {% else %} menu-btn"
                                {% endif %} href="{{ url_for('products') }}">Products</a>
            </div>

            <div class="right-side">
                {% if type!="new" %}
                    <a class="btn new-btn" href="new_{{ page }}">New</a>
                {% endif %}
            </div>

        </div>
{% block content %}
{% endblock %}

</html>

store_app/store/templates/bp/manipulate_client.html
{% extends "layout.html" %}
{% block content %}

            <div class="center">
                <form class="edit-form" name="Create client" method="post" novalidate>
                    {{ form.hidden_tag() }}
                    <div class="block">
                        {{ form.first_name.label }}
                        {{ form.first_name}}
                        {% for error in form.first_name.errors %}
                            <span class="error-message">{{ error }}</span>
                        {% endfor %}
                    </div>
                    <div class="block">
                        {{ form.last_name.label }}
                        {{ form.last_name }}
                        {% for error in form.last_name.errors %}
                            <span class="error-message">{{ error }}</span>
                        {% endfor %}
                    </div>
                    <div class="block">
                        {{ form.email.label }}
                        {{ form.email }}
                        {% for error in form.email.errors %}
                            <span class="error-message">{{ error }}</span>
                        {% endfor %}
                    </div>
                    <div class="block">
                        {{ form.phone.label }}
                        {{ form.phone }}
                        {% for error in form.phone.errors %}
                            <span class="error-message">{{ error }}</span>
                        {% endfor %}
                    </div>
                    <div class="edit">
                        {{ form.cancel( class_="cancel") }}
                        {{ form.submit( class_="save" ) }}
                    </div>
            </form>
        </div>


</body>
{% endblock %}

store_app/store/templates/bp/manipulate_order.html
{% extends "layout.html" %}
{% block content %}

            <div class="center">
                <form class="edit-form" name="Create order" method="post" novalidate>
                    {{ form.hidden_tag() }}
                        <div class="block">
                            {{ form.name.label }}
                            {{ form.name }}
                            {% for error in form.name.errors %}
                                <span class="error-message">{{ error }}</span>
                            {% endfor %}
                        </div>
                        <div class="block">
                            {{ form.phone.label }}
                            {{ form.phone }}
                            {% for error in form.phone.errors %}
                                <span class="error-message">{{ error }}</span>
                            {% endfor %}
                        </div>
                        <div class="block">
                            {{ form.order.label }}
                            {{ form.order }}
                            {% for error in form.order.errors %}
                                <span class="error-message">{{ error }}</span>
                            {% endfor %}
                        </div>
                        <div class="block">
                            {{ form.address.label }}
                            {{ form.address }}
                            {% for error in form.address.errors %}
                                <span class="error-message">{{ error }}</span>
                            {% endfor %}
                        </div>
                        <div class="block">
                            {{ form.date.label }}
                            {{ form.date (id_=date) }}
                            {% for error in form.date.errors %}
                                <span class="error-message">{{ error }}</span>
                            {% endfor %}
                        </div>
                        <div class="edit">
                            {{ form.cancel( class_="cancel") }}
                            {{ form.submit( class_="save" ) }}
                            </div>
            </form>
        </div>


</body>
{% endblock %}

store_app/store/templates/bp/manipulate_product.html
{% extends "layout.html" %}
{% block content %}
            <div class="center">
                <form class="edit-form" name="Create product" method="post" novalidate>
                        {{ form.hidden_tag() }}
                        <div class="block">
                            {{ form.name.label }}
                            {{ form.name }}
                            {% for error in form.name.errors %}
                                <span class="error-message">{{ error }}</span>
                            {% endfor %}
                        </div>
                        <div class="block">
                            {{ form.category.label }}
                            {{ form.category }}
                            {% for error in form.category.errors %}
                                <span class="error-message">{{ error }}</span>
                            {% endfor %}
                        </div>
                        <div class="block">
                            {{ form.year.label }}
                            {{ form.year }}
                            {% for error in form.year.errors %}
                                <span class="error-message">{{ error }}</span>
                            {% endfor %}
                        </div>
                        <div id="price-amount">
                            <div class="block">
                                {{ form.cost.label }}
                                {{ form.cost }}
                                {% for error in form.cost.errors %}
                                    <span class="error-message">{{ error }}</span>
                                {% endfor %}
                            </div>
                            <div class="block">
                                {{ form.amount.label }}
                                {{ form.amount }}
                                {% for error in form.amount.errors %}
                                    <span class="error-message">{{ error }}</span>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="edit">
                            {{ form.cancel( class_="cancel") }}
                            {{ form.submit( class_="save" ) }}
                        </div>
            </form>
        </div>


</body>
{% endblock %}

store_app/store/templates/bp/orders.html
{% extends "layout.html" %}
{% block content %}

        <div class="row">
                <form name="Filter", class="filter-form">
                    <div class="filter">
                    <label id="filter_by">Filter by date</label>
                    <span>{{ form.date_from.label }}
                        {{ form.date_from }}</span>
                    <span>{{ form.date_to.label }}
                    {{ form.date_to }}</span>
                        </div>
                    {{ form.refresh(class_="btn refresh-btn") }}

                </form>

        </div>
        <div class="list">
            <table class="table">
                <thead>
                    <tr>
                        <th class="column-id">Id</th>
                        <th class="column-client-id">User id</th>
                        <th class="column-items">Items</th>
                        <th class="column-date">Date</th>
                        <th class="column-cost">Cost</th>
                        <th class="column-address">Address</th>
                        <th class="column-edit"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in range(0, len) %}
                    <tr>
                        <td>{{ data[i].id }}</td>
                        {% if data[i].user_id==None %}
                            <td> - </td>
                        {% else %}
                            <td>{{ data[i].user_id }}</td>
                        {% endif %}
                        {% if order[i]=="" %}
                            <td class="deleted"> Deleted product </td>
                        {% else %}
                            <td>{{ order[i] }}</td>
                        {% endif %}

                        <td>{{ data[i].date }}</td>
                        <td>{{ data[i].cost }}</td>
                        <td>{{ data[i].address }}</td>
                        <td class="edit-row"><a href="{{ url_for('bp.delete_order', id=data[i].id) }}"><i class="fa-solid fa-trash-can"></i></a>
                            <a href="{{ url_for('bp.edit_order', id=data[i].id) }}"><i class="fa-solid fa-gear"></i></a></td>

                    </tr>
                   {% endfor %}

                </tbody>
            </table>
        </div>
    </div>

</body>
{% endblock %}

store_app/store/templates/bp/page_not_found.html
{% extends "layout.html" %}
{% block content %}
<div class="center">

    <h3>Oops! Page not found</h3>

</div>
{% endblock %}

store_app/store/templates/bp/products.html
{% extends "layout.html" %}
{% block content %}

        <div class="row">
                <form name="Filter", class="filter-form">
                    <div class="filter">
                    <label id="filter_by">Filter by price</label>
                    <span>{{ form.price_from.label }}
                        {{ form.price_from }}</span>
                    <span>{{ form.price_to.label }}
                    {{ form.price_to }}</span>
                        </div>
                    {{ form.refresh(class_="btn refresh-btn") }}

                </form>

        </div>
        <div class="list">
            <table class="table">
                <thead>
                    <tr>
                        <th class="column-id">Id</th>
                        <th class="column-name">Name</th>
                        <th class="column-price">Price</th>
                        <th class="column-category">Category</th>
                        <th class="column-year">Year</th>
                        <th class="column-amount">Amount</th>
                        <th class="column-edit"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in range(0, len) %}
                    <tr>
                        <td>{{ data[i].id }}</td>
                        <td>{{ data[i].name }}</td>
                        <td>{{ data[i].cost }}</td>
                        <td>{{ data[i].category }}</td>
                        <td>{{ data[i].year }}</td>
                        <td>{{ data[i].amount }}</td>
                        <td class="edit-row"><a href="{{ url_for('bp.delete_product', id=data[i].id) }}"><i class="fa-solid fa-trash-can"></i></a>
                            <a href="{{ url_for('bp.edit_product', id=data[i].id) }}"><i class="fa-solid fa-gear"></i></a></td>
                    </tr>

                    {% endfor  %}
                </tbody>
            </table>
        </div>
    </div>

</body>

{% endblock %}